name: Foundry project

on:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  CI: true
  FORK_RPC_URL: ${{ secrets.MAINNET_TESTS_FORK }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Use Latest Corepack
        run: |
          echo "Before: corepack version => $(corepack --version || echo 'not installed')"
          npm install -g corepack@latest
          echo "After : corepack version => $(corepack --version)"
          corepack enable
          pnpm --version

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version-file: ".nvmrc"

      - name: Install node dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Install forge dependencies
        run: forge i

      - name: Build project
        run: forge b

      - name: Run tests
        run: forge test --fork-url ${{ secrets.MAINNET_TESTS_FORK }}
