name: Foundry project

on:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  CI: true
  FORK_RPC_URL: ${{ secrets.MAINNET_TESTS_FORK }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Corepack for pnpm
        run: corepack enable

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version-file: ".nvmrc"

      - name: Install node dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install forge dependencies
        run: forge i

      - name: Build project
        run: forge b

      - name: Run tests
        run: forge test
